#!/bin/bash
# Stamps the build date and version into lib/version.js.
# Run before each build to update the home screen display.
set -euo pipefail

VERSION=$(node -e "console.log(require('./package.json').version)")
DATE=$(date '+%Y-%m-%d %H:%M')

cat > lib/version.js << EOF
// Auto-generated by scripts/stamp-version.sh — do not edit manually.
// Displays build date on the home screen.
BUILD_DATE = '$DATE';
BUILD_VERSION = '$VERSION';
EOF

echo "Stamped version $VERSION at $DATE"
